PREMIUM_BRANDS = {
    'MITSUBISHI ELECTRIC', 'VIESSMANN', 'BOSCH', 'DE DIETRICH',
    'BUDERUS', 'JUNKERS', 'WOLF', 'WESTEN'
}

BUDGET_BRANDS = {
    'ATLANTIC', 'FRISQUET', 'CHAPPEE', 'SAUNIER DUVAL',
    'PROTHERM', 'THERMOR', 'AQUATIS'
}